-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db744451699
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db744451699
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db744451699` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `db744451699` ;

-- -----------------------------------------------------
-- Table `db744451699`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db744451699`.`usuario` ;

CREATE TABLE IF NOT EXISTS `db744451699`.`usuario` (
  `codUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `rol` ENUM('admin', 'user') NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(100) NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `primerApellido` VARCHAR(45) NULL,
  `segundoApellido` VARCHAR(45) NULL,
  `imagenPerfil` VARCHAR(200) NULL,
  PRIMARY KEY (`codUsuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db744451699`.`terrenos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db744451699`.`terrenos` ;

CREATE TABLE IF NOT EXISTS `db744451699`.`terrenos` (
  `codTerreno` INT(11) NOT NULL AUTO_INCREMENT,
  `manzana` VARCHAR(15) NOT NULL,
  `codigoLote` VARCHAR(45) NULL,
  `lote` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `tamanio` VARCHAR(45) NULL,
  `escrituras` VARCHAR(45) NULL,
  `registroPropiedad` VARCHAR(45) NULL,
  `precio` DECIMAL(10,2) NULL,
  `inicial` DECIMAL(10,2) NULL,
  `saldo` DECIMAL(10,2) NULL,
  `vendido` ENUM('Si', 'Libre', 'En proceso') NULL,
  `fechaVenta` DATETIME NULL,
  `cuotas` VARCHAR(10) NULL,
  `montoPagar` DECIMAL(10,2) NULL,
  `cordenadas` TINYTEXT NULL,
  `cedulaComprador` VARCHAR(12) NULL,
  `nombresComprador` VARCHAR(45) NULL,
  `apellidosComprador` VARCHAR(45) NULL,
  `telefonoComprador` VARCHAR(20) NULL,
  `direccionComprador` VARCHAR(200) NULL,
  PRIMARY KEY (`codTerreno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db744451699`.`pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db744451699`.`pagos` ;

CREATE TABLE IF NOT EXISTS `db744451699`.`pagos` (
  `codPago` INT(11) NOT NULL AUTO_INCREMENT,
  `numeroCuota` INT(4) NULL,
  `fechaPago` DATETIME NULL,
  `formaPago` VARCHAR(45) NULL,
  `valor` DECIMAL(10,2) NULL,
  `saldoAFecha` DECIMAL(10,2) NULL,
  `comprobante` VARCHAR(200) NULL,
  `codTerreno` INT(11) NOT NULL,
  `codUsuario` INT(11) NOT NULL,
  `fechaCreacion` DATETIME NULL,
  PRIMARY KEY (`codPago`, `codTerreno`, `codUsuario`),
  INDEX `fk_pagos_terrenos_idx` (`codTerreno` ASC),
  INDEX `fk_pagos_usuario1_idx` (`codUsuario` ASC),
  CONSTRAINT `fk_pagos_terrenos`
    FOREIGN KEY (`codTerreno`)
    REFERENCES `db744451699`.`terrenos` (`codTerreno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_usuario1`
    FOREIGN KEY (`codUsuario`)
    REFERENCES `db744451699`.`usuario` (`codUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db744451699`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `db744451699`;
INSERT INTO `db744451699`.`usuario` (`codUsuario`, `rol`, `usuario`, `clave`, `nombres`, `primerApellido`, `segundoApellido`, `imagenPerfil`) VALUES (DEFAULT, 'admin', 'zirtrex', 'zirtrex', 'Rafael', 'Contreras', 'Martinez', NULL);
INSERT INTO `db744451699`.`usuario` (`codUsuario`, `rol`, `usuario`, `clave`, `nombres`, `primerApellido`, `segundoApellido`, `imagenPerfil`) VALUES (DEFAULT, 'user', 'manchundia', 'manchundia', 'MARIA EULALIA', 'ANCHUNDIA', 'PARRALES', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `db744451699`.`terrenos`
-- -----------------------------------------------------
START TRANSACTION;
USE `db744451699`;
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_2', NULL, '1', NULL, '200mts2', 'si', 'no', 10000, 2000, 8000, 'Si', '2017-04-15', '12', 800, NULL, NULL, 'Jorge Paladines', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_1', NULL, '2', NULL, NULL, 'no', 'si', , , , 'Libre', NULL, NULL, , NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_1', NULL, '3', NULL, NULL, 'no', 'no', 10000, 2000, 8000, 'En proceso', '2017-04-15', '36', 200, NULL, NULL, 'Max Paredes', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_24', NULL, '18', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'REGIS ALEXANDER ZAMBRANO MONCAYO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_16', NULL, '28', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JUANA DEL JESUS LEONES ORTEGA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_15', NULL, '31', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JESSICA ALAVA MENDOZA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_15', NULL, '32', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JESSICA ALAVA MENDOZA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_24', NULL, '19', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'VENESSA ANABELLA ZAMBRANO MONCAYO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_12', NULL, '32', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'BLANCA MARIA FERNANDA CEVALLOS CEVALLOS', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_22', NULL, '10', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'MARIBEL MARGARITA CEDEÑO VERA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_22', NULL, '35', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JORGE LEONEL ALCIVAR VERA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_25', NULL, '6', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ANGEL GONGORA Y SRA. IRMA MUÑOZ', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_6', NULL, '14', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'BOLIVAR RUIZ', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_4', NULL, '21', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'HUGO BELLETINI ANDRADE', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_19', NULL, '19', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'CURMENCINDO CALDERON RAMIREZ', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_8', NULL, '11', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'MARIANA GARCIA GARCIA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_11', NULL, '27', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ANGEL VILLATA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_E-1', NULL, '6', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JULIO ESMERALDA ZAMBRANO Y SRA.', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_13', NULL, '33', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'TEODORA VALAREZO ZAMBRANO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_D', NULL, '16', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'REINALDO CABEZAS VILLAVICENCIO Y SRA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_19', NULL, '12', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'GURMENCINDO CALDERON RAMIREZ', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_16', NULL, '12', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'PABLO CANDELA MERA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_15', NULL, '34', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'IRMA MUÑOZ Y NORMA MUÑOZ', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_E-2', NULL, '5', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ROSA CAGUA URETA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_20', NULL, '13', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'LIDIA ELSA ANDRADE VERA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_16', NULL, '21', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JOSE ASANZ', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_17', NULL, '15', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'SONIA MARGARITA VELIZ ZAMBRANO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_17', NULL, '19', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'AMBERTO MURILLO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_35', NULL, '15', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'EUDES NARCISA VERA MERA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_20', NULL, '18', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'CARMEN ALCIVAR ZAMBRANO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_20', NULL, '16', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ANDREZ ASANZ', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_15', NULL, '2', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ANGEL BELLOTE CORDERO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_19', NULL, '17', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'BOLIVAR Y LUISA ELENA CHIRIBOGA ZAMBRANO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_25', NULL, '13', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'XIMENA MAGALI ZAMBRANO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_18', NULL, '35', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ROSA MARIA PARRAGA JAMA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_14', NULL, '15', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'WALTER EILSON MEJIA MARTINEZ', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_18', NULL, '19', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'FULL MARIANO CONFORME VERA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_21', NULL, '22', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'GUILLER ANTONIO CALDERON ANDRADE', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_21', NULL, '23', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'PEDRO GABRIEL MERA FARIAS', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_19', NULL, '18', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JOHANA MARIBEL DELGADO MOREIRA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_25', NULL, '2', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ROSANNA ISABEL CEDEÑO RIVAS Y PEDRO PABLO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_6', NULL, '13', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'LUIS ALEJANDRO ZAMBRANO CISNERO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_11', NULL, '30', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JOSE ANTONIO LUQUE PALACIOS', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_13', NULL, '30', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'MARTHA OLIVA SANDOVAL DIAZ', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_13', NULL, '31', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'FRANCISCA ESTHER SALAZAR CHALARES', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_E-2', NULL, '1', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'DORA MARLENE HURTADO BRAVO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_18', NULL, '16', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JESSICA ALAVA MENDOZA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_18', NULL, '9', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'WILBERTO ALAVA MENDOZA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_18', NULL, '11', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'SOLANDA ORTIZ PILOSO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_18', NULL, '10', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'OSCAR ORTIZ', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_18', NULL, '12', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JESSICA ORTIZ', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_16', NULL, '23', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'AZUCENA PALLO MELENDEZ Y SU HIJA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_19', NULL, '18', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'MARLENE CALDERON RAMIREZ', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_23', NULL, '14', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JOSEFA CANCHINGRE CAMPO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_23', NULL, '13', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'SILVIA CAMPOS ESPINOZA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_10', NULL, '14', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ANA CANCHINGRE CAMPO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_18', NULL, '32', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'RAMON PATIÑO PATIÑO Y SRA.', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_21', NULL, '15', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'FERMIN RONQUILLO ANDRADE Y YAQUELINE FALCONES', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_21', NULL, '16', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'SANTA FALCONES LOPEZ', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_9', NULL, '21', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'CASTULO ESPINOZA VELASQUEZ', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_24', NULL, '20', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'EFREN EDUARDO PINTO MONCAYO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_25', NULL, '15', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'CECILIA DEL ROCIO CHICA N', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_D-A', NULL, '3', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'EUGENIA NARCISA CEVALLOS FRANCO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_23', NULL, '9', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JUAN CARLOS CEDEÑO RIVAS', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_23', NULL, '10', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JUAN CARLOS CEDEÑO RIVAS', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_23', NULL, '11', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JUAN CARLOS CEDEÑO RIVAS', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_21', NULL, '17', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'SANTA FALCONES LOPEZ', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_21', NULL, '18', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'SANTA FALCONES LOPEZ', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_16', NULL, '33', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'RAMON PATIÑO PATIÑO Y SRA.', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_16', NULL, '24', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'AZUCENA PALLO MELENDEZ Y SU HIJA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_E-2', NULL, '12', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'DORA MARLENE HURTADO BRAVO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_11', NULL, '31', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JOSE ANTONIO LUQUE PALACIOS', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_25', NULL, '19', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ROSANNA ISABEL CEDEÑO RIVAS Y PEDRO PABLO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_E-2', NULL, '6', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ROSA CAGUA URETA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_4', NULL, '22', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'HUGO BELLETINI ANDRADE', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_4', NULL, '23', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'HUGO BELLETINI ANDRADE', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_D', NULL, '17', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'REINALDO CABEZAS VILLAVICENCIO Y SRA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_D', NULL, '18', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'REINALDO CABEZAS VILLAVICENCIO Y SRA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_24', NULL, '7', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'GRICELDA DIOSELINA CAGUA CAGUA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_24', NULL, '16', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'CESAR ANTONIO CANCHINGRE MORALES', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_25', NULL, '5', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ANGELICA MARIA BURBANO ENDARA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_17', NULL, '16', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JESSICA ANAHI CHUSMO VELIZ', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_A', NULL, '6', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'GRACIELA MARIA FERNANDA GARCIA SALVADOR', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_16', NULL, '20', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'BLANCA FLOR DEL CARMEN INTRIAGO CAGUA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_D', NULL, '8', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JAVIER CUCALON GAILIOR Y SRA.', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_D', NULL, '9', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JAVIER CUCALON GAILIOR Y SRA.', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_27', NULL, '22', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JUAN CARLOS PATIÑO GOMEZ Y MARIA GARCIA MEJIA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_20', NULL, '3', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'BORIS CARLOS HERNANDEZ DELGADO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_27', NULL, '33', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'DARWIN OMAR ALCIVAR VERA Y SRA.', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_24', NULL, '9', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'BRIGIDO CUELLO ZAMBRANO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_D', NULL, '24', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'EDWIN RAMIRO IDROVO NARANJO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_9', NULL, '7', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JUAN JOSE RAMON VALLEJO ANDRADE', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_9', NULL, '8', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JUAN JOSE RAMON VALLEJO ANDRADE', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_18', NULL, '15', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ROSA MONICA DIAZ REYES', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_27', NULL, '29', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ROSA MONICA DIAZ REYES PARA SU HIJA AZUCENA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_27', NULL, '6', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'VICENTE CALLE RODRIGUEZ Y SRA.', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_D', NULL, '20', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ACASTULO ESPINOZA VELASQUEZ', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_24', NULL, '1', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'RAFAELA CASERES ZAMBRANO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_24', NULL, '2', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'RAFAELA CASERES ZAMBRANO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_17', NULL, '5', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'NORMA MARISOL CGABANIA VERGARA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_25', NULL, '8', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'CARLOS DANILO ZAMBRANO FARIAS', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_13', NULL, '19', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'OLGA RAMONA ZAMBRANO MEDRANO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_27', NULL, '9', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JOSE CECILIO DEFAZ FALCONES', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_28', NULL, '2', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ANA MARIA ANCHUNDIA PALADINES', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_28', NULL, '3', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'NORALBA RICARDINA ANCHUNDIA PALADINES', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_25', NULL, '3', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JOSE FARIAS SILVA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_15', NULL, '24', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JOSE ANTONIO PILOSO MEJIA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_17', NULL, '13', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'SANTO ALBERTO BONE QUIJIJE', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_20', NULL, '11', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ALVA CECILIA QUIÑONES MEJIA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_25', NULL, '7', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'FANNY ALVARES FALCONES', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_18', NULL, '2', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JUAN ANDRES LOOR FARIAS', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_19', NULL, '24', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'MERCEDES VENAVIDEZ ZAMBRANO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_27', NULL, '24', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ELIZABETH NANCY VILLACIS ECHANIQE', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_24', NULL, '23', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'LISBETH CAMERI PINTO MONCAYO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_27', NULL, '25', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ELIZABETH NANCY VILLACIS ECHANIQE', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_23', NULL, '12', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ANGEL BIENVENIDO CANCHINGRE CAMPO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_27', NULL, '28', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ROSA MONICA DIAZ REYES', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_20', NULL, '7', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'IVAN OLIVIO VIRIAS MOREIRA Y SRA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_8', NULL, '26', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'CARLOS CESAR PILLAJO QUINI Y SRA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_16', NULL, '8', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JORNY ALFREDO MERA GARCIA Y MARTHA ELOISA MACIAS', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_18', NULL, '29', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'JUAN MOREIRA Y NADIA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_20', NULL, '20', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'SANTA MAGDALENA ORTIZ CANCHINGRE', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_18', NULL, '32', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'MARIA ELENA MERA ZAMBRANO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_15', NULL, '1', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ANGEL COBA JARAMILLO Y SRA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_D', NULL, '20', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'RAMONA SOLEDISPA MERA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_12', NULL, '32', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'LEONARDO ALFREDO COBA CHIRIBOGA Y AZUCENA RAQUEL', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_17', NULL, '6', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'HUGO RAMIREZ JARAMILLO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_25', NULL, '24', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'LIORIA ESILDA MENDOZA CEDEÑO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_25', NULL, '4', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ALEXANDRA ROSANA CARRILLO FARIAS', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_12', NULL, '24', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'HECTOR EVELIO SOLORZANO MENDOZA Y SRA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_24', NULL, '14', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'RAMON VICENTE ZAMBRANO DELGADO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_18', NULL, '39', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'LUIS ANTONIO MERA VERA', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_18', NULL, '27', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'TANYA ZAMBRANO ANDRADE PARA SU HIJO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_19', NULL, '16', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ANGELICA GISSEL CHUMO RISO', NULL, NULL, NULL);
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (, 'Manzana_D', NULL, '23', NULL, NULL, 'si', 'si', , , , 'Si', NULL, NULL, , NULL, NULL, 'ANTONIO HUMBERTO ARIAS MANCHENO Y SRA', NULL, NULL, NULL);

COMMIT;

