-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db744451699
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db744451699
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db744451699` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `db744451699` ;

-- -----------------------------------------------------
-- Table `db744451699`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db744451699`.`usuario` ;

CREATE TABLE IF NOT EXISTS `db744451699`.`usuario` (
  `codUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `rol` ENUM('admin', 'user') NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(100) NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `primerApellido` VARCHAR(45) NULL,
  `segundoApellido` VARCHAR(45) NULL,
  `imagenPerfil` VARCHAR(200) NULL,
  PRIMARY KEY (`codUsuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db744451699`.`terrenos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db744451699`.`terrenos` ;

CREATE TABLE IF NOT EXISTS `db744451699`.`terrenos` (
  `codTerreno` INT(11) NOT NULL AUTO_INCREMENT,
  `manzana` VARCHAR(15) NOT NULL,
  `codigoLote` VARCHAR(45) NULL,
  `lote` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `tamanio` VARCHAR(45) NULL,
  `escrituras` VARCHAR(45) NULL,
  `registroPropiedad` VARCHAR(45) NULL,
  `precio` DECIMAL(10,2) NULL,
  `inicial` DECIMAL(10,2) NULL,
  `saldo` DECIMAL(10,2) NULL,
  `vendido` ENUM('Si', 'Libre', 'En proceso') NULL,
  `fechaVenta` DATETIME NULL,
  `cuotas` VARCHAR(10) NULL,
  `montoPagar` DECIMAL(10,2) NULL,
  `cordenadas` TINYTEXT NULL,
  `cedulaComprador` VARCHAR(12) NULL,
  `nombresComprador` VARCHAR(45) NULL,
  `apellidosComprador` VARCHAR(45) NULL,
  `telefonoComprador` VARCHAR(20) NULL,
  `direccionComprador` VARCHAR(200) NULL,
  PRIMARY KEY (`codTerreno`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigoLote` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db744451699`.`pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db744451699`.`pagos` ;

CREATE TABLE IF NOT EXISTS `db744451699`.`pagos` (
  `codPago` INT(11) NOT NULL AUTO_INCREMENT,
  `numeroCuota` INT(4) NULL,
  `fechaPago` DATETIME NULL,
  `formaPago` VARCHAR(45) NULL,
  `valor` DECIMAL(10,2) NULL,
  `saldoAFecha` DECIMAL(10,2) NULL,
  `comprobante` VARCHAR(200) NULL,
  `codTerreno` INT(11) NOT NULL,
  `codUsuario` INT(11) NOT NULL,
  `fechaCreacion` DATETIME NULL,
  PRIMARY KEY (`codPago`, `codTerreno`, `codUsuario`),
  INDEX `fk_pagos_terrenos_idx` (`codTerreno` ASC),
  INDEX `fk_pagos_usuario1_idx` (`codUsuario` ASC),
  CONSTRAINT `fk_pagos_terrenos`
    FOREIGN KEY (`codTerreno`)
    REFERENCES `db744451699`.`terrenos` (`codTerreno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_usuario1`
    FOREIGN KEY (`codUsuario`)
    REFERENCES `db744451699`.`usuario` (`codUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db744451699`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `db744451699`;
INSERT INTO `db744451699`.`usuario` (`codUsuario`, `rol`, `usuario`, `clave`, `nombres`, `primerApellido`, `segundoApellido`, `imagenPerfil`) VALUES (DEFAULT, 'admin', 'zirtrex', 'zirtrex', 'Rafael', 'Contreras', 'Martinez', NULL);
INSERT INTO `db744451699`.`usuario` (`codUsuario`, `rol`, `usuario`, `clave`, `nombres`, `primerApellido`, `segundoApellido`, `imagenPerfil`) VALUES (DEFAULT, 'user', 'manchundia', 'manchundia', 'MARIA EULALIA', 'ANCHUNDIA', 'PARRALES', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `db744451699`.`terrenos`
-- -----------------------------------------------------
START TRANSACTION;
USE `db744451699`;
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_2', '', '1', '', '200mts2', 'si', 'no', 10000, 2000, 8000, 'Si', '2017-04-15', '12', 800, '', '', 'Jorge Paladines', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_1', '', '2', '', '', 'no', 'si', , , , 'Libre', '', '', , '', '', '', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_1', '', '3', '', '', 'no', 'no', 10000, 2000, 8000, 'En proceso', '2017-04-15', '36', 200, '', '', 'Max Paredes', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_24', '', '18', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'REGIS ALEXANDER ZAMBRANO MONCAYO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_16', '', '28', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JUANA DEL JESUS LEONES ORTEGA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_15', '', '31', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JESSICA ALAVA MENDOZA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_15', '', '32', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JESSICA ALAVA MENDOZA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_24', '', '19', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'VENESSA ANABELLA ZAMBRANO MONCAYO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_12', '', '32', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'BLANCA MARIA FERNANDA CEVALLOS CEVALLOS', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_22', '', '10', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'MARIBEL MARGARITA CEDEÑO VERA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_22', '', '35', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JORGE LEONEL ALCIVAR VERA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_25', '', '6', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ANGEL GONGORA Y SRA. IRMA MUÑOZ', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_6', '', '14', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'BOLIVAR RUIZ', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_4', '', '21', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'HUGO BELLETINI ANDRADE', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_19', '', '19', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'CURMENCINDO CALDERON RAMIREZ', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_8', '', '11', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'MARIANA GARCIA GARCIA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_11', '', '27', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ANGEL VILLATA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_E-1', '', '6', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JULIO ESMERALDA ZAMBRANO Y SRA.', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_13', '', '33', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'TEODORA VALAREZO ZAMBRANO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_D', '', '16', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'REINALDO CABEZAS VILLAVICENCIO Y SRA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_19', '', '12', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'GURMENCINDO CALDERON RAMIREZ', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_16', '', '12', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'PABLO CANDELA MERA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_15', '', '34', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'IRMA MUÑOZ Y NORMA MUÑOZ', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_E-2', '', '5', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ROSA CAGUA URETA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_20', '', '13', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'LIDIA ELSA ANDRADE VERA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_16', '', '21', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JOSE ASANZ', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_17', '', '15', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'SONIA MARGARITA VELIZ ZAMBRANO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_17', '', '19', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'AMBERTO MURILLO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_35', '', '15', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'EUDES NARCISA VERA MERA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_20', '', '18', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'CARMEN ALCIVAR ZAMBRANO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_20', '', '16', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ANDREZ ASANZ', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_15', '', '2', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ANGEL BELLOTE CORDERO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_19', '', '17', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'BOLIVAR Y LUISA ELENA CHIRIBOGA ZAMBRANO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_25', '', '13', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'XIMENA MAGALI ZAMBRANO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_18', '', '35', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ROSA MARIA PARRAGA JAMA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_14', '', '15', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'WALTER EILSON MEJIA MARTINEZ', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_18', '', '19', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'FULL MARIANO CONFORME VERA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_21', '', '22', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'GUILLER ANTONIO CALDERON ANDRADE', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_21', '', '23', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'PEDRO GABRIEL MERA FARIAS', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_19', '', '18', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JOHANA MARIBEL DELGADO MOREIRA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_25', '', '2', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ROSANNA ISABEL CEDEÑO RIVAS Y PEDRO PABLO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_6', '', '13', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'LUIS ALEJANDRO ZAMBRANO CISNERO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_11', '', '30', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JOSE ANTONIO LUQUE PALACIOS', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_13', '', '30', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'MARTHA OLIVA SANDOVAL DIAZ', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_13', '', '31', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'FRANCISCA ESTHER SALAZAR CHALARES', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_E-2', '', '1', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'DORA MARLENE HURTADO BRAVO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_18', '', '16', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JESSICA ALAVA MENDOZA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_18', '', '9', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'WILBERTO ALAVA MENDOZA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_18', '', '11', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'SOLANDA ORTIZ PILOSO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_18', '', '10', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'OSCAR ORTIZ', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_18', '', '12', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JESSICA ORTIZ', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_16', '', '23', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'AZUCENA PALLO MELENDEZ Y SU HIJA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_19', '', '18', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'MARLENE CALDERON RAMIREZ', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_23', '', '14', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JOSEFA CANCHINGRE CAMPO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_23', '', '13', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'SILVIA CAMPOS ESPINOZA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_10', '', '14', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ANA CANCHINGRE CAMPO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_18', '', '32', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'RAMON PATIÑO PATIÑO Y SRA.', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_21', '', '15', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'FERMIN RONQUILLO ANDRADE Y YAQUELINE FALCONES', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_21', '', '16', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'SANTA FALCONES LOPEZ', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_9', '', '21', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'CASTULO ESPINOZA VELASQUEZ', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_24', '', '20', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'EFREN EDUARDO PINTO MONCAYO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_25', '', '15', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'CECILIA DEL ROCIO CHICA N', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_D-A', '', '3', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'EUGENIA NARCISA CEVALLOS FRANCO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_23', '', '9', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JUAN CARLOS CEDEÑO RIVAS', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_23', '', '10', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JUAN CARLOS CEDEÑO RIVAS', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_23', '', '11', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JUAN CARLOS CEDEÑO RIVAS', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_21', '', '17', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'SANTA FALCONES LOPEZ', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_21', '', '18', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'SANTA FALCONES LOPEZ', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_16', '', '33', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'RAMON PATIÑO PATIÑO Y SRA.', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_16', '', '24', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'AZUCENA PALLO MELENDEZ Y SU HIJA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_E-2', '', '12', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'DORA MARLENE HURTADO BRAVO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_11', '', '31', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JOSE ANTONIO LUQUE PALACIOS', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_25', '', '19', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ROSANNA ISABEL CEDEÑO RIVAS Y PEDRO PABLO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_E-2', '', '6', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ROSA CAGUA URETA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_4', '', '22', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'HUGO BELLETINI ANDRADE', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_4', '', '23', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'HUGO BELLETINI ANDRADE', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_D', '', '17', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'REINALDO CABEZAS VILLAVICENCIO Y SRA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_D', '', '18', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'REINALDO CABEZAS VILLAVICENCIO Y SRA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_24', '', '7', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'GRICELDA DIOSELINA CAGUA CAGUA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_24', '', '16', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'CESAR ANTONIO CANCHINGRE MORALES', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_25', '', '5', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ANGELICA MARIA BURBANO ENDARA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_17', '', '16', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JESSICA ANAHI CHUSMO VELIZ', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_A', '', '6', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'GRACIELA MARIA FERNANDA GARCIA SALVADOR', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_16', '', '20', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'BLANCA FLOR DEL CARMEN INTRIAGO CAGUA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_D', '', '8', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JAVIER CUCALON GAILIOR Y SRA.', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_D', '', '9', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JAVIER CUCALON GAILIOR Y SRA.', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_27', '', '22', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JUAN CARLOS PATIÑO GOMEZ Y MARIA GARCIA MEJIA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_20', '', '3', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'BORIS CARLOS HERNANDEZ DELGADO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_27', '', '33', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'DARWIN OMAR ALCIVAR VERA Y SRA.', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_24', '', '9', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'BRIGIDO CUELLO ZAMBRANO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_D', '', '24', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'EDWIN RAMIRO IDROVO NARANJO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_9', '', '7', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JUAN JOSE RAMON VALLEJO ANDRADE', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_9', '', '8', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JUAN JOSE RAMON VALLEJO ANDRADE', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_18', '', '15', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ROSA MONICA DIAZ REYES', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_27', '', '29', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ROSA MONICA DIAZ REYES PARA SU HIJA AZUCENA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_27', '', '6', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'VICENTE CALLE RODRIGUEZ Y SRA.', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_D', '', '20', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ACASTULO ESPINOZA VELASQUEZ', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_24', '', '1', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'RAFAELA CASERES ZAMBRANO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_24', '', '2', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'RAFAELA CASERES ZAMBRANO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_17', '', '5', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'NORMA MARISOL CGABANIA VERGARA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_25', '', '8', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'CARLOS DANILO ZAMBRANO FARIAS', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_13', '', '19', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'OLGA RAMONA ZAMBRANO MEDRANO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_27', '', '9', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JOSE CECILIO DEFAZ FALCONES', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_28', '', '2', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ANA MARIA ANCHUNDIA PALADINES', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_28', '', '3', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'NORALBA RICARDINA ANCHUNDIA PALADINES', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_25', '', '3', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JOSE FARIAS SILVA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_15', '', '24', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JOSE ANTONIO PILOSO MEJIA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_17', '', '13', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'SANTO ALBERTO BONE QUIJIJE', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_20', '', '11', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ALVA CECILIA QUIÑONES MEJIA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_25', '', '7', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'FANNY ALVARES FALCONES', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_18', '', '2', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JUAN ANDRES LOOR FARIAS', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_19', '', '24', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'MERCEDES VENAVIDEZ ZAMBRANO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_27', '', '24', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ELIZABETH NANCY VILLACIS ECHANIQE', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_24', '', '23', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'LISBETH CAMERI PINTO MONCAYO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_27', '', '25', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ELIZABETH NANCY VILLACIS ECHANIQE', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_23', '', '12', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ANGEL BIENVENIDO CANCHINGRE CAMPO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_27', '', '28', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ROSA MONICA DIAZ REYES', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_20', '', '7', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'IVAN OLIVIO VIRIAS MOREIRA Y SRA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_8', '', '26', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'CARLOS CESAR PILLAJO QUINI Y SRA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_16', '', '8', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JORNY ALFREDO MERA GARCIA Y MARTHA ELOISA MACIAS', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_18', '', '29', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'JUAN MOREIRA Y NADIA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_20', '', '20', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'SANTA MAGDALENA ORTIZ CANCHINGRE', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_18', '', '32', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'MARIA ELENA MERA ZAMBRANO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_15', '', '1', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ANGEL COBA JARAMILLO Y SRA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_D', '', '20', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'RAMONA SOLEDISPA MERA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_12', '', '32', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'LEONARDO ALFREDO COBA CHIRIBOGA Y AZUCENA RAQUEL', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_17', '', '6', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'HUGO RAMIREZ JARAMILLO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_25', '', '24', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'LIORIA ESILDA MENDOZA CEDEÑO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_25', '', '4', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ALEXANDRA ROSANA CARRILLO FARIAS', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_12', '', '24', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'HECTOR EVELIO SOLORZANO MENDOZA Y SRA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_24', '', '14', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'RAMON VICENTE ZAMBRANO DELGADO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_18', '', '39', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'LUIS ANTONIO MERA VERA', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_18', '', '27', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'TANYA ZAMBRANO ANDRADE PARA SU HIJO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_19', '', '16', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ANGELICA GISSEL CHUMO RISO', '', '', '');
INSERT INTO `db744451699`.`terrenos` (`codTerreno`, `manzana`, `codigoLote`, `lote`, `nombre`, `tamanio`, `escrituras`, `registroPropiedad`, `precio`, `inicial`, `saldo`, `vendido`, `fechaVenta`, `cuotas`, `montoPagar`, `cordenadas`, `cedulaComprador`, `nombresComprador`, `apellidosComprador`, `telefonoComprador`, `direccionComprador`) VALUES (DEFAULT, 'Manzana_D', '', '23', '', '', 'si', 'si', , , , 'si', '', '', , '', '', 'ANTONIO HUMBERTO ARIAS MANCHENO Y SRA', '', '', '');

COMMIT;

